import Navbar from '@/components/navbar/Navbar'
import './globals.scss'
import { Inter } from 'next/font/google'
import GlobalContainer from '@/utils/GlobalContainer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContainer>
          <Navbar />
          {children}
        </GlobalContainer>
      </body>
    </html>
  )
}
