import Navbar from '@/components/navbar/Navbar'
import './globals.scss'
import { Poppins } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: 'Rohan Poudel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body className={poppins.className} suppressHydrationWarning={true}>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html >
  )
}
